replicaCount: 2

image:
  repository: MY_DOCKERHUB_ID/argocd-gitactions-app  # MY_DOCKERHUB_ID: 본인의 Docker Hub ID로 변경
  pullPolicy: IfNotPresent
  # CI 파이프라인이 이 태그를 빌드 번호(예: latest -> 1 -> 2 -> 3 -> ...)로 계속 변경합니다.
  tag: "3"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080  # Boot App 포트